- cname.list
> Add dedenf.thedev.id

- cname.list
> Add eagleanurag.thedev.id

- cname.list
SO many thanks for the team for creating this nifty, free way of making website domains for developers! It's amazing nowadays when you can connect with many people around the world to create such massive projects.
> Add trungbot.thedev.id

- cname.list
> Add wiktor.thedev.id

- cname.list
Hello, thanks for this really amazing project and supporting devs. 
CNAME: https://github.com/iddev5/iddev5.github.io/blob/master/CNAME
> Add ayush.thedev.id

- cname.list
Just added my name to the list. 
Thanks for making this project, it's really nice :)
> Add harshdev.thedev.id

- cname.list
Please add my github pages aalfiann.github.io
Thank you bro..
> Add aalfiann.thedev.id

- cname.list
Hello! I would like to have a subdomain for my website. I hope I did everything right.
GitHub Repository - https://github.com/Aktindo/aktindo.github.io
Cheers,
Aktindo
> aktindo.thedev.id

- cname.list
Hello!
Thanks for providing the service. cname file location https://github.com/dattw/dattw.github.io/blob/main/CNAME
Not too sure what to do really, I hope I've done it right.
> Add ttw.thedev.id

- cname.list
[CNAME link](https://github.com/AnilSeervi/LinkYard/blob/master/CNAME)
> Add anil.thedev.id

- cname.list
[CNAME link](https://github.com/TheBotlyNoob/TheBotlyNoob.github.io/blob/main/CNAME)
> Add jj.thedev.id

- cname.list
> Add bd103.thedev.id

- cname.list
https://github.com/nikhilmwarrier/nikhilmwarrier.github.io/blob/main/CNAME
Thanks for this wonderful service! 😃
> Add nikhil.thedev.id

- cname.list
- subdomains.json
Link to my CNAME: https://github.com/NoelJacob/NoelJacob.github.io/blob/master/CNAME
And thank you guys for this😊.
> Added noel.thedev.id

- README.md
As mentioned in this pull request #107, in @fransallen's comment [here](https://github.com/fransallen/thedev.id/pull/107#issuecomment-869175514).
I thought it's useful to add the requirement for having the JSON file alphabetically sorted before submitting the pull request.
> Add alphabetical order notice

- subdomains.json
> faris.thedev.id

- subdomains.json
I have got my own domain now so I no longer need this one
> Remove kaleko.thedev.id

- subdomains.json
> add: andy.thedev.id

- subdomains.json
> Add fastering18.github.io

- CNAME
- subdomains.json
> Add iprasetya.thedev.id

- subdomains.json
Keep making awesome products, mas!
> add sinulingga.thedev.id

- subdomains.json
add afif.thedev.id from bungambohlah.vercel.app as CNAME
> build: :wrench: add subdomains for me (afif)

- subdomains.json
> Adding subdomain

- subdomains.json
Sorry yang sebelumnya ada kesalahan teknis jadi request lagi
This is my personal web page for freelancing
> Add devinesia.thedev.id

- subdomains.json
As requested I did `npm install` and `npm run sort` and opened up another Pull Request adding infoblock.github.io to the subdomains.json
> infoblock.github.io

- subdomains.json
This is my personal website for portofolio
Thank you
> feat: fikri.vercel.app domain

- subdomains.json
sorry for the late response, was having quite a hectic few weeks
> added subdomain for timkenhan

- subdomains.json
I see no one claming `david` yet, so here it goes. 
The domain is pointed to my personal website. 
Cheers 🍻
> Add david subdomain

- subdomains.json
> Remove domain

- subdomains.json
Adding my subdomain, thank you
> add mhmmd-ysf

- subdomains.json
Hi,
Ini sangat keren, mohon review PR saya dan kiranya bisa ditambahkan sebagai subdomain di thedev.id
Regards,
Arwafiles
> Please approve me - arwanfiles

- subdomains.json
> Added carter domain and sorted

- subdomains.json
just added my blog url to subdomain.json, hosted on vercel. and I hope it works
> sorted blog-halip26

- subdomains.json
this is my personal website. 
Thanks
> add new subdomains

- subdomains.json
> add new domain ihsan

- subdomains.json
Requested Subdomain:
paban
My site:
https://pabanjyoti.github.io/
> add subdomain "paban"

- subdomains.json
> add domain at subdomains.json

- subdomains.json
Hello, creating a subdomain for my portfolio site. Thank you!
> Add saksham.thedev.id

- subdomains.json
> Add new domain gornostay25

- README.md
Hi @fransallen, since my project based on Indonesia vibes, would you adding this reference in `Similar Service` to grow my audience as well
> chore: add merahputih.moe as it Similar Services

- subdomains.json
Updated subdomains.json to add kdaui to the list :) .
> Updated subdomains.json for kdaui
